### ISSUE TITLE
BUG I CAN'T TYPE PKG UPDATE

### ISSUE THREAD

**Issue by cleondotb** [termux-play-store/termux-issues#11]
### Problem description

Metadata integrity can't be verified, repository is disabled now.

### What steps will reproduce the bug?

idk

### What is the expected behavior?

GPG Error

### System information

```shell
pkg update
```

**Comment by fornwall** [comment]
Could you paste the complete output of running `pkg update`, as well as running `termux-info`?

**Comment by fornwall** [comment]
The problem will be fixed shortly - will post an update here!

**Comment by fornwall** [comment]
The good news is that the issue has been fixed in version `1.3` of the `termux-exec` package!

To update from the currently bad installation, either:
1. Await version `0.129` of the Termux app to be out on Google Play (should be in 1-3 days), then uninstall and install again, or
2. Run `apt --allow-insecure-repositories update`. Then run `apt upgrade` and write `y` to the two questions - this should get you the good update (version `1.3` of the `termux-exec` package). Then exit the session and start a new one, and now `pkg` should work as desired.

Sorry for the problems, and let me know how it works or if you have any questions!
