### ISSUE TITLE
[Bug]:Gpg error

### ISSUE THREAD

**Issue by Redboomax** [termux-play-store/termux-issues#12]
### Problem description

GPG error: https://termux.net stable InRelease: Couldn't execute /data/data/com.termux/files/usr/bin/apt-key to check /data/data/com.termux/files/usr/var/lib/apt/lists/partial/termux.net_dists_stable_InRelease
Error: The repository 'https://termux.net stable InRelease' is not signed.
Notice: Metadata integrity can't be verified, repository is disabled now.

### What steps will reproduce the bug?

I dont know im asking about the way to solve it

### What is the expected behavior?

.

### System information

```shell
.
```

**Comment by fornwall** [comment]
Thanks for reporting the issue!

Could you provide additional information such as your Android version and phone model name? It would be really helpful!

Also, could you also paste the output from running `apt-key list`?

**Comment by Redboomax** [comment]
My android version 11
My phone redmi note 8pro


Le mar. 18 juin 2024 à 13:36, Fredrik Fornwall ***@***.***> a
écrit :

**Comment by fornwall** [comment]
Thanks a lot for your report! I have identified the problem - will fix it shortly and post an update here.

**Comment by fornwall** [comment]
The good news is that the issue has been fixed in version `1.3` of the `termux-exec` package!

To update from the currently bad installation, either:
1. Await version `0.129` of the Termux app to be out on Google Play (should be in 1-3 days), then uninstall and install again, or
2. Run `apt --allow-insecure-repositories update`. Then run `apt upgrade` and write `y` to the two questions - this should get you the good update (version `1.3` of the `termux-exec` package). Then exit the session and start a new one, and now `pkg` should work as desired.

Sorry for the problems, and let me know how it works or if you have any questions!
