### ISSUE TITLE
termux-setup-storage not working

### ISSUE THREAD

**Issue by OMISKING11** [termux-play-store/termux-issues#2]
### Problem description

Whenever I use this command in termux termux-setup-storage my app closes and when I reopen it it says [1]

### What steps will reproduce the bug?

Let me know

### What is the expected behavior?

It should create a file repository

### System information

```shell
[1]
```

**Comment by fornwall** [comment]
Hi! This is fixed in version `0.125`,  that is awaiting review from Google and should be available within a day or two. Let me know how it works after having that update!

Due to Android system behaviour changes, exactly what files `termux-setup-storage` gives access to will change compared to before:
- On Android 12 or earlier all files are accessible like before under `~/storage/`.
- On Android 13 or later only media (images, audio and video) files will be accessible in `~/storage/` - there will be commands added to fetch other non-media document types into Termux soon, to complement the raw file system access to media files.

**Comment by fornwall** [comment]
The `0.126` build is now out on Google Play!
