### ISSUE TITLE
[Bug]: The new update is not allowing access to storage.

### ISSUE THREAD

**Issue by LiUmAyKoM** [termux-play-store/termux-issues#3]
### Problem description

Termux v122 is unable to access the Storage.
![Screenshot_2024-06-11-21-31-40-254_com termux](https://github.com/termux-play-store/termux-issues/assets/116598517/a3b39f42-c859-4e89-99fe-87bb701f324b)

### What steps will reproduce the bug?

When starting an installation of DarkOS, a Windows emulator.

### What is the expected behavior?

I don't know.

### System information

```shell
Android 14, Hyper OS 1.0.2.0
```

**Comment by fornwall** [comment]
Thanks for reporting! This is fixed in version `0.125`,  that is awaiting review from Google and should be available within a day or two. Let me know how it works after having that update!

Due to Android system behaviour changes, exactly what files `termux-setup-storage` gives access to will change compared to before:
- On Android 12 or earlier all files are accessible like before under `~/storage/`.
- On Android 13 or later only media (images, audio and video) files will be accessible in `~/storage/` - there will be commands added to fetch other non-media document types into Termux soon, to complement the raw file system access to media files.

**Comment by fornwall** [comment]
As this is already reported i #2, I'm closing this one - please track #2 for updates and feedback after the `0.125` update is out!
