### ISSUE TITLE
[Bug]: /data/data is almost empty

### ISSUE THREAD

**Issue by my456l** [termux-play-store/termux-issues#7]
### Problem description

I'm using termux 0.126 on Android 14, rooted by Magisk. When I access /data/data, it's almost empty except com.termux and com.google.android.gms. I have run termux-setup-storage and granted permissions.

### What steps will reproduce the bug?

~ $ su
:/data/data/com.termux/files/home # cd /data/data
:/data/data # ls
com.google.android.ms    com.termux
:/data/data #

### What is the expected behavior?

Access /data/data/ completely.

### System information

```shell
Termux Variables:
unsupported
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
Updatable packages:
debianutils/stable 5.19 aarch64 [upgradable from: 5.18]
termux-tools/stable 3.0.6 all [upgradable from: 3.0.4]
termux-tools version:
3.0.4
Android version:
14
Kernel build information:
Linux localhost 5.15.123-android13-8-00008-g3ca6a2912c7e-ab11087001 #1 SMP PREEMPT Sat Nov 11 06:58:10 UTC 2023 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
2211133C
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by fornwall** [comment]
This is a limitation when targeting newer Android versions (which is necessary to be on Google Play): https://developer.android.com/about/versions/11/privacy/storage

Since you are rooted there might be a way around this perhaps - probably best to reach out to the Magisk community and ask for help (and if you find out anything, it would be valuable if you could share that ❤️).

If you find out that there is any improvement that can be done on the Termux side, please open a new issue!
